### ISSUE TITLE
Armor Event Issue

### ISSUE THREAD

**Issue by Brokeos** [Inkzzz/ArmorEvent#1]
Hello !

I have a problem with your plugin.

When the player equip an Armor with a dispenser, I have an error : 

> [23:13:09 ERROR]: Could not pass event PlayerInteractEvent to ArmorEvent v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-43]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-PaperSpigot-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-PaperSpigot-43]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:382) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:663) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(PacketPlayInBlockPlace.java:86) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:789) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-43]
Caused by: java.lang.NullPointerException
        at com.inkzzz.spigot.armorevent.EventAnalyser.onEvent(EventAnalyser.java:68) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor866.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-PaperSpigot-43]
        ... 15 more

Can you fix it please ? :)

**Comment by Inkzzz** [comment]
Hello,

I have fixed this issue. 

You can download the new version here - `https://www.spigotmc.org/resources/armor-event-1-7-1-8-1-9.24111/`. 

Reason:
The bug was occurring due to your 1.7 spigot use. However, I have fixed the issue for you.

Kind Regards,

Inkzzz.

**Comment by Brokeos** [comment]
Thanks.

But when the player is equipped by a dispenser your plugin doesn't work ! :/

**Comment by Brokeos** [comment]
And when is destroyed by damage, the same things !

PS: Sorry if i don't write english very fine i'm french ! :(

**Comment by Inkzzz** [comment]
Hello,

All the above issues have been fixed. If you find any other bugs, or requests, please make a new issue report.

Kind Regards,

Inkzzz.
