### ISSUE TITLE
Armor Event Issue (again)

### ISSUE THREAD

**Issue by Brokeos** [Inkzzz/ArmorEvent#2]
Hi, I found an other issue

First, when I dispense an armor I have an error:

> [13:51:03 ERROR]: Could not pass event BlockDispenseEvent to ArmorEvent v1.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-PaperSpigot-43]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-PaperSpigot-43]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot.jar:git-PaperSpigot-43]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.DispenseBehaviorItem.a(DispenseBehaviorItem.java:57) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.DispenseBehaviorItem.b(DispenseBehaviorItem.java:26) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.DispenseBehaviorItem.a(DispenseBehaviorItem.java:13) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.BlockDispenser.dispense(BlockDispenser.java:82) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.BlockDispenser.a(BlockDispenser.java:110) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.WorldServer.a(WorldServer.java:593) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.WorldServer.doTick(WorldServer.java:211) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:745) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-PaperSpigot-43]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-43]
Caused by: java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDD)Ljava/util/Collection;
        at com.inkzzz.spigot.armorevent.EventAnalyser.onEvent(EventAnalyser.java:115) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_102]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_102]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-PaperSpigot-43]
        ... 15 more

And I the event isn't called.

Can you fix it ? :p

**Comment by Inkzzz** [comment]
Hello,

New methods not supported by 1.7. 

... Armor Event is no longer supported in 1.7.
