### ISSUE TITLE
EventAnalyser$1.run(EventAnalyser.java:151)

### ISSUE THREAD

**Issue by tomasmessing** [Inkzzz/ArmorEvent#4]
[12:43:19] [Server thread/WARN]: [ArmorEvent] Task #15 for ArmorEvent v1.3 generated an exception
java.lang.NullPointerException
	at com.inkzzz.spigot.armorevent.EventAnalyser$1.run(EventAnalyser.java:151) ~[?:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-90f61bc-83a9dbd]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by Inkzzz** [comment]
Hello,

I have resolved this issue.

You can download the new version [here](https://www.spigotmc.org/resources/armor-event-1-8-1-9-1-10.24111/).

Kind Regards,

Inkzzz.
